### ISSUE TITLE
About Eigen 

### ISSUE THREAD

**Issue by DUT-XYZ** [Elias-Gu/MPM2D#3]
A very excellent code of MPM. I saw a version using Eigen. But Snow and Elastic are not included in that code.  can them run based on Eigen? Because i am trying to convert your code to 3D mode and algerbra.h cannot use like Vector3f. however, 3D elastic  and snow cannot run successfully.

**Comment by Elias-Gu** [comment]
Right now snow and elastic materials are not included in the Eigen implementation, although it shouldn't be too complicated to include them (just need to switch the `Matrix2f` and `Vector2f` stuff to their `Eigen` versions). As for 3d, it will be a bit more labor intensive since all the x-y loops will need to be changed to x-y-z. For vectors and matrices I agree that it would make sense to use `Eigen` then.
I don't plan on making these changes right now but might get to it in the future.
